charts/ditto/Chart.yaml
charts/ditto/templates/NOTES.txt
charts/ditto/templates/nginx-route.yaml
charts/ditto/values.yaml

This change adds support for deploying an OpenShift route, when setting `routes.enabled= true` (which is false by default) .

Allow creating an OpenShift route

---

.github/workflows/ci.yaml

Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>
* only run when changes in charts dir
* fix timeout issue (configured timeout was not used as relative path for ct config file is needed)
* put lint bash scripts in own job
* updated kubernetes node versions to latest kind images
This will fix https://github.com/eclipse/packages/issues/16

improve helm ci pipline

---

.github/ct.yaml

The original timeout of 7200 caused the installation to fail after 2
hours. Installation of charts should never take that long.
6 minutes seems to be a reasonable amount of time after which
installation can be considered to have failed.

Reduce timeout for helm install command

---

CONTRIBUTING.md
homepage/about.html
homepage/contribute.md

It seems feasible to define some constraints and requirements regarding
the quality of the charts being hosted in the IoT Packages project.
This includes documentation, functionality, compliance etc.
The requirements have been copied (and slightly adapted) from the
central Helm Chart repo's CONTRIBUTING guide on GitHub.

Add requirements for charts

---

.github/workflows/ci.yaml

* Use helm repo for github action again as https://github.com/helm/kind-action/pull/16 has been merged
* updated k8s versions
* removed k8s 1.11 as storage class install fails there
* fixes node image varname
* added cluster version to step name …

[helm ci] Use helm repo for github action

---

charts/hono/Chart.yaml
charts/hono/requirements.yaml

This PR is intended for the issue eclipse/hono#1728 to upgrade the Prometheus version to 2.15.2.

[eclipse/hono#1728] Update Prometheus to version 2.15.2

---

charts/hono/Chart.yaml
charts/hono/templates/NOTES.txt
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-secret.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-secret.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-secret.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-secret.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-secret.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-secret.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-secret.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-secret.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

This allows for users to create and mount extra secrets for e.g.
providing device registry data and or custom permission definitions used
by the Auth Server while still using the example keys for TLS.
Also adapted the NOTES.txt to display some more useful information.

Always include example key material in conf secret

---

charts/hawkbit/Chart.yaml

The key word can be used to filter for project charts when searching the
repository.

Add iot-chart key word to hawkBit Chart.yaml

---

homepage/_packages/cloud2edge/installation.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/values.yaml

For a demo setup, the Ditto components should also be able to work with fewer resources than defined by the Ditto chart.
Adapt installation instructions on home page to refer to output of helm
install command.
Changed chart version to allow installation without --devel flag.

Set resource limits for all components

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/post-install/hono-connection.json

Regarding the target address for cloud-2-device direction (commands).
The used address pattern `command/<tenant>/<device-id>` was still the pattern used in older versions of Hono.
Removed the `/<device-id>` part.

fixed that Ditto-Hono connection in c2e package contained wrong address

---

charts/hono/Chart.yaml
charts/hono/templates/example-data-grid/service.yaml
charts/hono/templates/example-data-grid/statefulset.yaml

The `is_healthy.sh` script for some reason took >= 30 secs to complete.
Changed the readiness probe to connect to the hotrod port instead.

[#61] Use hotrod port for readiness probe

---

charts/hono/Chart.yaml
charts/hono/config/router/qdrouterd.json
charts/hono/templates/dispatch-router/dispatch-router-ext-svc.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-ext-svc.yaml
charts/hono/values.yaml

The example AMQP Messaging Network and Device Registry can now be
configured to allow protocol adapters that run outside of the cluster to
connect to their secure endpoints.
This is helpful e.g. for connecting edge nodes which run a Hono protocol
adapter to connect to a Hono instance running in a back end.

Support connecting external protocol adapters

---

.github/ct.yaml
.github/kubeval.sh
.github/lint-scripts.sh
.github/workflows/ci.yaml

kubeval is a tool for validating a Kubernetes YAML or JSON configuration file. It does so using schemas generated from the Kubernetes OpenAPI specification, and therefore can validate schemas for multiple versions of Kubernetes.
changes:
* added kubeval to github actions pipeline
* removed rm from lint-scripts.sh (is removed anyway)
* added chart-dirs option to ct.yaml to use packages dir too
info: 
* https://github.com/instrumenta/kubeval
* https://kubeval.instrumenta.dev/

added kubeval to github actions pipeline

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/config/router/qdrouterd.json
charts/hono/templates/_helpers.tpl
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-secret.yaml
charts/hono/values.yaml

The example registry's Dispatch Router and Artemis containers can now be
configured to mount additional secret volumes. This way, the router and
broker can be configured with custom key material.
The example regstry's Dispatch Router's "internal" listener can now be
configured with the uidFormat and to use for extracting user IDs from
client certificate subject DNs. This is needed in order to properly
configure the protocol adapter uids when using custom certificates from
your own PKI.

Add support for mounting additional secrets in broker and router

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-statefulset.yaml

Somehow, this slipped back in: https://github.com/eclipse/hono/issues/1007

Upon restart, file base device registry configuration is overwritten

---

charts/hono/Chart.yaml
charts/hono/ci/datagrid-values.yaml
charts/hono/ci/device-connection-service-values.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-secret.yaml
charts/hono/values.yaml

The protocol adapters now connect directly to an Infinispan data grid if
either the example grid is enabled or connection properties for an
existing grid are explicitly configured.
I have also added two more `ci/*-values.yaml` files for testing deployment with data grid.

Prefer direct connection to data grid for device connection data

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/jaeger/jaeger-collector-service.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/templates/jaeger/jaeger-query-service.yaml
charts/hono/templates/prometheus/prometheus-config.yaml
charts/hono/values.yaml

The tchannel protocol has been deprecated in Jaeger. The gRPC protocol
is the recommended way for collecting spans from Agents.
Updated to Jaeger 1.17 as well.

Use gRPC for collecting spans

---

charts/ditto/Chart.yaml
charts/ditto/values.yaml

adjusted defaults for CPU requests for Ditto chart in order to be able to start on a 2 CPU core machine

Reduce default CPU requests for Ditto chart

---

.github/workflows/ci.yaml

The CI pipeline now verifies installation to kubernetes 1.18.0. Older
versions have beeen updated to their latest patch version.
1.12 has been removed.

[#86] Add kubernetes 1.18.0

---

.github/workflows/ci.yaml

The k8s versions supported by the *chart-testing install* are the tags available for the `kindest/node` image which seem to lag behind the *official* kubernetes releases

Fix k8s versions for install test in CI pipeline

---

.github/kubeval.sh
.github/workflows/ci.yaml

Signed-off-by: André Bauer <monotek23@gmail.com>
* updated kubeval config to use k8s 1.17.4
* added kubeval config for k8s 1.18.1
* updated helm client to 3.1.2
* updated kubeval to 01.5.0
this is a follow up to: https://github.com/eclipse/packages/pull/90
new kubeval configs available from:  https://github.com/instrumenta/kubernetes-json-schema

update kubeval 1.17 and added 1.18

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-statefulset.yaml
charts/hono/values.yaml

The chart has supported configuration of the container image name for
all components already. However, the tag name has been part of the image
name so far. In order to allow setting the version of all Hono
components in one go, the honoImagesTag property has been introduced
which defaults to the chart's appVersion. The property can be used for
example to use not yet released (milestone) images for experimenting
purposes. All of Hono's components also support a specific *imageTag*
property to set the image's tag name per component.

Make tag name of Hono images configurable

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-secret.yaml

The 10.1 Hotrod client used in the upcoming Hono 1.3.0 requires explicit
specification of the "auth_realm" when authenticating using the
DIGEST-MD5 SASL mechanism.

[#115] Fix issues connecting to Infinispan 11

---

charts/hono/Chart.yaml
charts/hono/requirements.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-statefulset.yaml
charts/hono/templates/prometheus/prometheus-config.yaml

Changed Prometheus server config to discover pods to be scraped
dynamically using the k8s API server.
Also updated to Prometheus 2.19.0.

Use annotation based Prometheus scraping configuration

---

charts/hono/.gitignore
charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl

The adapters can now also be configured to retrieve resource usage data
from an existing Prometheus server.

Support existing Prometheus server

---

charts/hawkbit/.gitignore
charts/hawkbit/Chart.yaml
charts/hawkbit/requirements.lock
charts/hawkbit/requirements.yaml

This fixes errors when packaging the Hawkbit chart:
````
Downloading mysql from repo https://charts.bitnami.com
Save error occurred:  could not find : chart mysql not found in https://charts.bitnami.com
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart mysql not found in https://charts.bitnami.com
````
I've also removed the `requirements.lock` file and added it to `.gitignore` (in analogy to how it's done in the Hono chart).

Fix repo URLs in Hawkbit requirements

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/post-install/hono-connection.json
packages/cloud2edge/requirements.yaml

* use Hono 1.3.0
* use Ditto 1.2.0
* configure Ditto/Hono connection template to:
* configure Ditto "acknowledgementRequests" to activate QoS 1 processing for Hono messages with "qos" header set to "1"
* configure a "replyTarget" for consumed telemetry/event messages from Hono - when the Ditto Protocol payload message contains a "reply-to" header, a response is sent back to that address
I thought using the newest minor versions of Hono/Ditto is worth a minor update of the c2e package, so I chose version `0.1.0`.
What do you think?

updated cloud2edge package to latest Ditto+Hono

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/requirements.yaml

Upgrade Hono dependency in Cloud2Edge package to the one with the recreated demo keys/certs (#136).

[#136] Use Hono chart with new demo keys/certs in c2e

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-statefulset.yaml
charts/hono/values.yaml

The container registry to pull Hono images from can now be configured
for each image separately, falling back to a globally defined Hono
container registry.

[#129] Support configuring the container registry for Hono images

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

This is for #142:
Allow Hono device identifiers to contain a colon, as required by Ditto.
Also fix some typos.

[#142] Use deviceIdPattern with added colon

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/post-install/demo-device-credentials.json
packages/cloud2edge/requirements.yaml

This fixes #142.
Use updated Hono chart with fix to allow device identifiers to contain a colon, as required by Ditto.
Remove invalid "device-id" fields in credentials json.

[#142] Use updated Hono chart; fix credentials json

---

charts/hono/Chart.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml

We'd like for Hono format its logging in json. The least intrusive way to do that is to just provide a custom log config. The biggest drawback I see here is that we (at Aloxy) have to maintain our own logconfig.
Alternatively, Hono could include a configuration for json logging, where you could switch between normal/json with a single variable here.

allow overriding logconfig

---

charts/hono/Chart.yaml
charts/hono/example/add_example_data_device_registry.sh
charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-svc.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

The default name used by the MongoDB chart for creating the
corresponding Kubernetes Service will cause a name clash with the
"HONO_MONGO_DB" configuration variable of the MongoDB based registry
when using "hono" as the Helm release name during installation.
Overriding the chart's name with "mongodb-server" prevents this from
happening.

Avoid config property name clash

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/dispatch-router/dispatch-router-ext-svc.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-svc.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-svc.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-svc.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-svc.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-svc.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-svc.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-svc.yaml
charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-ext-svc.yaml

We'd like to run this in 2 separate namespaces in a single cluster, so ports have to be configurable.
Also; all of these services are configured as either LoadBalancer or NodePort. Why is that? It would be far easier if this would be either LoadBalancer or ClusterIp, for http at least.
Any ideas @ctron @dejanb? 
Signed-off-by: Dirk Van Haerenborgh <dirk.vanhaerenborgh@aloxy.io>

make service ports configurable

---

charts/hono/Chart.yaml
charts/hono/templates/artemis/artemis-deployment.yaml

With this fix, now it should be able to mount the additional secrets specified in `values.yaml` into the Artemis container's file system.

[#155] Fix mounting of additional secrets into the Artemis container's filesystem

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-secret.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-secret.yaml

The Quarkus based adapters expect to find the `application.yaml` file in
the `config` folder relative to the current working directory.
The working directory in the Quarkus based images had been changed to
`/opt/hono` recently so the mount path for the config secret has been adapted
accordingly.

Fix location of Quarkus config file

---

charts/hono/Chart.yaml

I would like to bump the *chart* version to 1.5.0 once we use any of the new features introduced in Hono 1.5.0, e.g. supporting to configure the Command Router and/or the JDBC registry. For now, the chart's config properties all remain the same, we are just updating to the *latest and greatest* Hono ;-)

Upgrade to Hono 1.5.0

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

Add support for using JDBC based device & tenant registry in the Hono Helm chart. 
JDBC based device registries will be part of the upcoming Hono 1.5.0 release.
Fixes #163 
* Hono 1.5.0 (not release yet)
* For testing with custom images, this change helps:
* https://github.com/eclipse/hono/pull/2322 
* for example: `mvn clean install -Pbuild-docker-image,metrics-prometheus && ./push_hono_images.sh 1.5.0-SNAPSHOT mycustomcr.azurecr.io`
* For SQLServer support (works with Azure SQL Database)
* https://github.com/eclipse/hono/pull/2317
* For fixes for Postgres support
* https://github.com/eclipse/hono/pull/2317

[hono] Add support for JDBC device registry

---

.github/ct.yaml
.github/kubeval.sh
.github/workflows/ci.yaml

Replacing the obsolete "https://kubernetes-charts.storage.googleapis.com"
location and adding prometheus and grafana repos.

Fix repo URLs in GitHub Actions workflow

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/values.yaml

This PR addresses #167 and enables the user to set the certificate configuration and respective paths of the amqpMessagingNetworkSpec through the values.yaml file of the Hono Chart. Please note, that @LuLeRoemer joined the work on this PR.

[#167] adds configuration option for certificates in dispatch router of Eclipse Hono Chart

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/values.yaml

The application profiles that should be active for the (Spring based)
adapters and services as well as the Spring Boot and logging config file
locations can now be configured via properties of the values.yaml file.

Support configuration of Spring Boot environment variables

---

charts/hawkbit/Chart.yaml
charts/hawkbit/requirements.yaml
charts/hawkbit/templates/ingress.yaml

The previous api version is deprected and is removed on kubernetes 1.16, therefore, updating it.

Update ingress to comply with kubernetes 1.16

---

.github/kind-config.yaml
.github/workflows/ci.yaml

The chart linter and kind deploy confiugrations have been updated to the
latest kubernetes versions.
The helm/kind-action has been upgraded to the latest minor version
(1.1.0).

Update to latest kubernetes version(s)

---

charts/hono/Chart.yaml
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/values.yaml

As indicated in the title, this PR adds the option to set the qdrouterd.json file location from the values.yaml of the Hono chart. The default values is the previously hard-coded value from the dispatch-router-deployment.yaml file.

allow to set qdrouterd.json location through values.yaml of Hono chart

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl

This PR extends the 'defineSecretVolumeMounts' in the _helpers.tpl used within the Hono chart to also consider the 'subPath' property.
Note, since the previous PR #187 increases the version field to 1.4.22, this PR already sets the version to 1.4.23. Therefore, I propose to merge the other PR (#187) before this PR.

add 'subPath' support for secretVolumeMounts in Hono chart

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/requirements.yaml
packages/cloud2edge/values.yaml

The Hono chart's registry is now configured to use Ditto's Mongo DB
instance.

[#152] Use Mongo DB based device registry by default

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml

The gateway-based auto-provisioning feature requires that the device registry connects to the AMQP messaging network. The necessary configuration is added here.
This is a preparation for Hono 1.6.

Add messaging config for device registries

---

charts/ditto/Chart.yaml
charts/ditto/nginx-config/nginx-cors.conf
charts/ditto/templates/swaggerui-deployment.yaml

* for some browsers, usage of "*" for "Access-Control-Allow-Origin" is forbidden - fix that
* add "PATCH" verb
* white-list all HTTP headers

fixed nginx CORS config for Ditto chart

---

charts/hono/Chart.yaml
charts/hono/config/infinispan/hono-data-grid.xml

[#198] Fix 'command-router' cache not being defined

---

charts/hono/Chart.yaml
charts/hono/config/artemis/broker.xml
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-route.yaml

This fixes #200:
Using the HOME env variable value used in the Artemis image to prevent errors creating the /var/run/artemis/custom
directory as a non-root user in OpenShift.
Also fixing the Qdrouter Route definition.

[#200] Fix Artemis startup in OpenShift

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/requirements.yaml
packages/cloud2edge/values.yaml

This fixes #202:
With the switch to the Hono MongoDB-based device registry (not containing a device connection service implementation like the file-based one does) in the cloud2edge chart (#152), there is no device connection service implementation getting deployed anymore, leading to Hono command & control errors. 
Therefore the "deviceConnectionService.enabled" option is set here to deploy the device connection service component, using an embedded cache (newer Hono chart version needed for that).

[#202] Enable Hono Device Connection service

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-http-route.yaml

The http device registry route was pointing to the `amqps` endpoint, which should point to the `http` endpoint. 
Tested on okd 4.7 with `curl`.

fixed device registry http route wrongly pointing to amqps endpoint

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl

An "Always" "imagePullPolicy" will only be used on SNAPSHOT images if the image name doesn't
start with "index.docker.io/eclipse/". 
This simplifies usage of self-built images with standard names in minikube. And the "index.docker.io" registry doesn't contain "eclipse/*" SNAPSHOT images anyway.

Hono: Adapt setting of 'Always' pull policy

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/example/example-permissions.json
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

- Replace deprecated `ADMIN_HTTP_PORT` Jaeger all-in-one property and update Jaeger images to 1.22
- Update Infinispan to 11.09
- Add tenant service configuration for command router component (needed in Hono 1.7.0) and update Hono to 1.7.0

Update Hono to 1.7.0

---

charts/hono/Chart.yaml
charts/hono/example/certs/trust-anchor.properties
charts/hono/example/create_certs.sh
charts/hono/example/default_tenant-trusted-ca.json
charts/hono/example/example-tenants.sh

Updates the Hono chart to Hono 1.7.1 and fixes the wrong DEFAULT_TENANT trusted-ca data in `example.tenants.sh` (see https://github.com/eclipse/hono/issues/2628).

Update to Hono 1.7.1, fix example-tenants.sh

---

charts/hono/Chart.yaml
charts/hono/README.md

This fixes #224.
Also adds info on mounting the secret for the Command Router service.
(Note that even with the Command Router service being used, the `commandAndControlSpec` is still expected to be below `adapters` - for compatibility with the configuration using the old device connection service (`useCommandRouter: false`). This shall get changed in a later chart update.)

[#224] Fix info in README on mounting AMQP network secret

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/example/jaeger/default-sampling-strategies.json
charts/hono/templates/_helpers.tpl
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/templates/jaeger/jaeger-secret.yaml
charts/hono/values.yaml

The Jaeger Collector can serve sampling strategies for individual
services to Agents from a central configuration file.
The chart now uses this approach to define a default "sample everything"
strategy and distribute it to all Hono components' side car Agent
containers.
The sampling strategies can be configured in a custom file as well which
can be mounted as an extra secret into the Jaeger all-in-one container.

Use back end to centrally manage Jaeger sampling strategy

---

.github/kubeval.sh
.github/workflows/ci.yaml
charts/hono/Chart.yaml
homepage/prereqs.md

The chart-testing-action version 2 has introduced some breaking changes.
in particular, it now installs the chart testing tool instead of
wrapping it. Thus invocation of the `ct` command line tool needs to be
adapted.
Also changed the `kubeval.sh` script to no longer install helm as this is now
done by the `ci.yml` workflow.
Also removed outdated k8s versions from the install-chart job.

Fix CI build

---

homepage/_packages/cloud2edge/installation.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/example-permissions.json
packages/cloud2edge/requirements.yaml
packages/cloud2edge/values.yaml

Changed Hono configuration to use Command Router instead of (deprecated) Device Connection service.

Update c2e package to use latest Hono and Ditto releases

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/_helpers.tpl
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/templates/prometheus/prometheus-config.yaml

(Relates to https://github.com/eclipse/packages/pull/236.)
Fixes these 4 issues:
1. chart jaeger sampling strategies file isn't getting used
2. quarkus service names in strategies file don't match
3. tracing for quarkus-native images doesn't work
4. jaeger metrics are not getting scraped 
Adding
````
- name: LOG_LEVEL
value: debug
- name: SAMPLING_STRATEGIES_RELOAD_INTERVAL
value: 3s
````
env vars to the Jaeger all-in-one deployment reveals that the configured sampling strategies file isn't actually used:
````
{"level":"info","ts":1621436711.2852476,"caller":"static/strategy_store.go:181","msg":"Updated sampling strategies:{\n  \"default_strategy\": {\n    \"type\": \"probabilistic\",\n    \"param\": 1\n  }\n}\n"}
{"level":"debug","ts":1621436732.8051255,"caller":"static/strategy_store.go: …
```

Fix usage of jaeger sampling strategies, fix metrics scraping

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry-embedded/headless-svc.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-pvc.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/values.yaml

This resolves #234. It should not be merged before Hono 1.8.0 is released because it depends on [a feature](https://github.com/eclipse/hono/issues/2587) that will be available from this version on.
This PR adds `embedded` as a new type of example device registry. The embedded device registry uses the existing JDBC device registry implementation and activates the application profile `create-schema` on it. The device registration database, as well as the tenant database, are H2 databases stored on a persisted volume.

[#234] Add embedded JDBC-based Device Registry

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/values.yaml

This improves #235
The JDBC based registry, when used with an embedded H2 DB, will require
more memory to accommodate the additional H2 DB functionality.
The resource requests and limits of the device registry can now also be
set at the particular registry type level, falling back to the default
values specified at the registry example level.

Request more memory for embedded device registry type

---

charts/ditto/Chart.yaml
charts/ditto/templates/concierge-deployment.yaml
charts/ditto/templates/connectivity-deployment.yaml
charts/ditto/templates/gateway-deployment.yaml
charts/ditto/templates/nginx-deployment.yaml
charts/ditto/templates/policies-deployment.yaml
charts/ditto/templates/swaggerui-deployment.yaml
charts/ditto/templates/things-deployment.yaml
charts/ditto/templates/thingssearch-deployment.yaml
charts/ditto/values.yaml

With this PR it is possible to configure Ditto to log to a logstash endpoint.
It is also possible to pipe logs into log files.
Add initContainers to Ditto deployments in order to write log files in the _/var/log/dittto_ directory on the host.
Add initContainer to nginx deployment to wait until the gateway service is ready.

Extend Ditto logging configuration options

---

.jenkins/Jenkinsfile

Helm 3 is required now, otherwise packaging the Hono chart fails.
Corresponding manually triggered Jenkins run (via Replay) is at https://ci.eclipse.org/packages/job/Website/job/master/153/.

Use Helm 3 in Jenkinsfile

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/profileKafkaMessaging.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/values.yaml

Instead of selecting one messaging type with the property `messagingNetworkType`, the messaging configuration is now selected with the property `messagingNetworkTypes` that allows setting more than one value. This is intended to be used for the deployment of Hono's sandbox, where both messaging networks should be enabled simultaneously.

Hono: Enable parallel usage of AMQP and Kafka messaging

---

charts/hono/Chart.yaml
charts/hono/README.md

This adds documentation of the properties that are required to use services of type 'NodePort' instead of type 'LoadBalancer' to the readme of the Hono chart.

[Hono] Add NodePort deployment to Hono readme

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml

This fixes #260. It adds support for Kafka-based messaging to the device registry with an embedded database.

[#260] Hono: Support Kafka based messaging in embedded Device Registry

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl

Adds client configuration for cases in which the example Kafka broker is configured to allow unencrypted connections from clients. This is intended to be used in the Hono Sandbox.

Hono: Allow to disable TLS on example Kafka deployment

---

charts/hono/Chart.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-secret.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-svc.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-svc.yaml

The "Command Router" and "Device Connection Service" components are no longer exposed to the outside of the Kubernetes cluster.
PS: I just saw that I pushed by accident a very small fix for the Auth service config. I'll leave it here because it's really small and obvious :)

[Hono] Do not expose Command Router and Device Connection Service.

---

charts/hono/Chart.yaml
charts/hono/values.yaml

This fixes #267. 
It configures the example Kafka cluster that can be deployed with Hono to expose the standard Kafka port 9092 for external access. Before the port 9094 was used as an external port and 9092 was used only internally in the Kubernetes cluster. This commit changes both ports.

[#267] Hono: Use standard Kafka port for external access.

---

charts/hono/Chart.yaml
charts/hono/config/infinispan/hono-data-grid.xml
charts/hono/templates/_helpers.tpl
charts/hono/templates/example-data-grid/statefulset.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/values.yaml

The example data grid currently uses the standard infinispan/server
image which uses a lot of memory. The infinispan/server-native image is
based on a Quarkus native binary which uses fewer memory and starts up
much quicker. It can therefore help to reduce the overall memory
footprint and improve start up time of the overall Hono instance.
Fixes #271

Use Infinispan server native image

---

charts/hono/Chart.yaml
charts/hono/values.yaml

This defines a node port for the external service of the example Kafka broker.

Hono: Set node port for external Kafka service.

---

charts/hono/Chart.yaml
charts/hono/ci/device-connection-service-values.yaml
charts/hono/ci/quarkus-native-images-values.yaml
charts/hono/values.yaml

The Deviec Connection CI profile has been adapted to use the Spring Boot
based images.

Use Quarkus based images by default

---

charts/hono/Chart.yaml
charts/hono/requirements.yaml
charts/hono/templates/grafana/grafana-datasource-secret.yaml
charts/hono/values.yaml

Preventing deprecation warnings regarding 'rbac.authorization.k8s.io/v1beta1' api version:
````
W0817 13:33:20.344759   86807 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0817 13:33:20.347629   86807 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0817 13:33:20.350211   86807 warnings.go:70] rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
W0817 13:33:20.353586   86807 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use …
```

Update Prometheus and Grafana chart versions

---

charts/hono/Chart.yaml
charts/hono/config/grafana/dashboard-definitions/jvm-details.json
charts/hono/config/grafana/dashboard-definitions/message-details.json
charts/hono/config/grafana/dashboard-definitions/overview.json

- Replace `$__range` with `$__rate_interval`. 
If a Hono protocol adapter pod gets deleted and a new one gets started, a large chart time range would otherwise result in an  equally large period being displayed with wrong (doubled) chart values.
- Replace `$__interval` with `$__rate_interval`. 
This prevents empty rate/irate() results in case of a short range (with not enough data points in `$__interval`) being displayed.

Fix rate()/irate() Hono dashboard queries

---

charts/hono/Chart.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

https://github.com/jaegertracing/jaeger/issues/3022 has been fixed in
Jaeger All-in-One 1.23

Remove workaround for defining Jaeger sampling strategy

---

.github/workflows/ci.yaml

Noticing a "segmentation fault" on the CI run of PR #288, I checked our current tool versions and found e.g. Helm at 3.1 (current version 3.7).
I went ahead and updated the Helm versions in our GitHub workflow: a) in the hope this fixes the segmentation fault b) because I think it is time to (conservatively) update to a newer version.

update tool versions

---

charts/hono/Chart.yaml
charts/hono/values.yaml

The "defaultJavaOptions" property had never been used in any of the
templates. Instead, the JDK_JAVA_OPTIONS environment variable set on the
containers had been created with the value of component specific
properties.

[Hono] Remove obsolete configuration property

---

charts/hono/Chart.yaml
charts/hono/values.yaml

The default Kafka broker configuration is adapted here to allow deletion of topics.
This is relevant for the `hono.command_internal.[adapterInstanceId]` topics, created by Hono for the lifetime of a protocol adapter instance after which they shall get deleted.
Relates to https://github.com/eclipse/hono/issues/2901.

[Hono] Enable deletion of Kafka topics

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/values.yaml

Wrong property name was used in `_helpers.tpl` and in the documentation.

Fix usage of springLoggingConfig

---

charts/hono/Chart.yaml
charts/hono/templates/example-data-grid/statefulset.yaml
charts/hono/values.yaml

Update Infinispan to version with updated log4j (CVE-2021-44228). Using the non-native image since there are no native versions of the current Infinispan releases.

Update Infinispan image to 11.0.13.Final

---

charts/hono/Chart.yaml
charts/hono/ci/device-connection-service-values.yaml
charts/hono/requirements.yaml
charts/hono/templates/NOTES.txt
charts/hono/values.yaml

The dependency on the Kafka chart has been changed to version 14.
The default internal and external ports defined in the Kafka chart are
now being used unaltered.

Upgrade Kafka chart

---

charts/hono/Chart.yaml
charts/hono/requirements.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

Use (most recent) chart that installs Mongo DB 4.4 to reflect what we already use in Hono's unit and integration tests

Upgrade Mongo DB chart

---

charts/hono/Chart.yaml
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/templates/example-data-grid/statefulset.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-post-install-job.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

This pull request allows to pull images in Hono chart from private registry (e.g. using a proxy registry in enterprise infrastructure). Other charts already provide this option. I've used the approach from default helm template. But it is a valid discussion how to unify it across other charts. I intentionally din't use "global" value from Ditto chart since it conflicts with bitnami dependencies which use the same value with different yaml format.

Added imagePullSecrets to hono chart for pulling from private registries

---

charts/hono/Chart.yaml
charts/hono/ci/mongodb-based-device-registry-values.yaml
charts/hono/config/command-router/embedded-cache-config.xml
charts/hono/config/infinispan/hono-data-grid.xml
charts/hono/templates/NOTES.txt
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/values.yaml

- Updated Infinispan configuration schema to version 13
- Use in-memory data store for embedded cache in Command Router instead
of file-store based cache (which does not work with network file system
anyway)
- Added support for explicitly configuring cache usage in Command Router
- Made information output after successful deployment more specific to
the security configuration used with example Kafka cluster

Several improvements

---

charts/hono/Chart.yaml
charts/hono/ci/mongodb-based-device-registry-values.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

The "auth.tls.existingSecrets" property in the Kafka chart does not work
as documented. Falling back to the (deprecated but working)
"auth.tls.existingSecret" property.
Also updating to latest Hono service release.
Fixes #339

[#339] Use deprecated property to configure TLS keys

---

.github/ct.yaml
.github/workflows/ci.yaml
homepage/_packages/cloud2edge/tour.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/README.md
packages/cloud2edge/example-permissions.json
packages/cloud2edge/post-install/thing-definition.json
packages/cloud2edge/requirements.yaml
packages/cloud2edge/templates/NOTES.txt
packages/cloud2edge/values.yaml

Use current Hono and Ditto versions (including updated Hono example certificates).
Also apply some minor corrections.

Cloud2Edge: Update Hono and Ditto dependencies

---

charts/hono/Chart.yaml
charts/hono/config/logging-quarkus-dev.yaml
charts/hono/config/logging-quarkus-prod.yaml
charts/hono/config/logging-quarkus-trace.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-secret.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-secret.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-vertx-secret.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
charts/hono/templates/hono-adapter-kura/hono-adapter-kura-secret.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-vertx-secret.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-secret.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-secret.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

The logging level(s) used in the Quarkus based components can now be set
using the "quarkusLoggingProfile" configuration property that is defined
for all components for which a Quarkus based variant exists.
Fixes #303

[#303] Support setting log level in Quarkus based images

---

charts/hono/Chart.yaml
charts/hono/config/artemis/broker.xml
charts/hono/config/artemis/liveness-probe.sh
charts/hono/config/artemis/readiness-probe.sh
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/artemis/artemis-secret.yaml

The k8s readiness and liveness probes have been changed to no longer use
a TCP connection attempt but to instead query the broker state via the
Jolokia HTTP API.
Fixes #345

Use Jolokia HTTP API for k8s probes

---

charts/hono/Chart.yaml
charts/hono/requirements.yaml
charts/hono/templates/grafana/grafana-dashboard-jvm-configmap.yaml
charts/hono/templates/grafana/grafana-dashboard-message-details-configmap.yaml
charts/hono/templates/grafana/grafana-dashboard-overview-configmap.yaml
charts/hono/values.yaml

Always use latest minor versions of Prometheus and Grafana charts.
Also split up ConfigMap containing Grafana dashboard definitions into
separate ConfigMaps, each containing a single dashboard definition as
recommended by the Grafana chart documentation.

Upgrade to latest latest monitoring chart minor versions

---

charts/ditto/Chart.yaml
charts/ditto/README.md
charts/ditto/templates/gateway-deployment.yaml
charts/ditto/values.yaml

ENABLE_DUMMY_AUTH was replaced by ENABLE_PRE_AUTHENTICATION.
You can see that here https://github.com/eclipse/ditto/blob/e25c34e044b2d4c0428874942fa75e078c74ce82/gateway/service/src/main/resources/gateway.conf
I replaced ENABLE_DUMMY_AUTH with ENABLE_PRE_AUTHENTICATION in the README.md, values.yaml and gateway-deployment.yaml accordingly.
I don't know if backward compatibility is required nether I found an easy way to introduce it because the env-variables would affect each other.

Ditto: Replace enableDummyAuth by enablePreAuthentication

---

charts/ditto/Chart.yaml
charts/ditto/templates/concierge-deployment.yaml
charts/ditto/templates/connectivity-deployment.yaml
charts/ditto/templates/gateway-deployment.yaml
charts/ditto/templates/policies-deployment.yaml
charts/ditto/templates/swaggerui-networkpolicy.yaml
charts/ditto/templates/things-deployment.yaml
charts/ditto/templates/thingssearch-deployment.yaml
packages/cloud2edge/profileKafkaMessaging.yaml
packages/cloud2edge/templates/post-install-job.yaml
packages/cloud2edge/values.yaml

Because swagger ui definition is loaded from Github during start of container.

Remove egress from policyType for swaggerui-networkpolicy.yaml 

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/prometheus/prometheus-config.yaml

Using the standard HTTP scheme will allow the chart to be used with Hono
2.0.0 container images as well. That is because Hono 2.0.0 uses SmallRye
Health to spin up an http server hosting the health check and readiness
endpoints and the http server's default configuration does not use HTTPS
and uses other configuration properties than Hono 1.x's custom rolled
health check server.
Using HTTP by default shouldn't be a big issue because the health check
server's endpoints are not exposed via k8s services anyway.
Also updated to Hono 1.12.2

Use HTTP scheme for health checks and probes

---

charts/hawkbit/Chart.yaml
charts/hawkbit/requirements.yaml

This resolves #372, applying the workaround mentioned in https://github.com/bitnami/charts/issues/10539.

[#372] Apply workaround for unavailable bitnami dependencies

---

.github/workflows/ci.yaml

Adapt chart testing to use five most recent k8s versions.
Update tools for chart testing to latest versions
The change to the Hono chart version has been made to trigger the testing of the Hono chart. The change should be reverted before merging ...

Adopt latest k8s versions

---

charts/hono/Chart.yaml
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/values.yaml

This sets the default container to be used by "kubectl logs" or "kubectl exec". The `kubectl.kubernetes.io/default-container` annotation has been introduced with Kubernetes 1.21.
Also fixes outdated links in values.yaml documentation.

Hono: Add default-container annotation

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/ci/quarkus-native-images-values.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/values.yaml

The Hono chart already supports setting JAVA_OPTIONS to be passed to the
Hono containers. These options can be used to e.g. specify the amount of
memory to use. However, the native executable variants of the Hono
containers ignore the JAVA_OPTIONS but instead require passing options
as command line arguments to set memory limits etc.
The values.yaml now contains a cmdLineArgs property for each component
which can be used to specify an array of Strings to be passed as command
line arguments to the container's CMD.

Add support for passing command line arguments to container CMDs

---

charts/hono/Chart.yaml
charts/hono/config/artemis/broker.xml
charts/hono/config/artemis/launch.sh
charts/hono/config/artemis/liveness-probe.sh
charts/hono/config/artemis/readiness-probe.sh
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/artemis/artemis-secret.yaml
charts/hono/values.yaml

This fixes #383:
No newer version of "enmasse/artemis-base" available, therefore switching to another Artemis image.
This updates Artemis from 2.16.0 to 2.23.0 and updates the used OpenJDK version from 11.0.3 to 17.0.3.
The JDK update fixes the keystore loading issue.
The basic Artemis broker image from https://github.com/artemiscloud/activemq-artemis-broker-image is used here.
Using the extended image version for Kubernetes (https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image) may also be an option. It has a lot more configuration options and we could use it to move some of the `broker.xml` adaptations into separate environment variables (e.g. the SSL config). At first glance, I don't see though, how the `<wildcard-addresses/>` and `default-address-routing-type` …

[#383] Use "artemiscloud/activemq-artemis-broker" image

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/_helpers.tpl
charts/hono/templates/artemis/artemis-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/templates/example-data-grid/statefulset.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

This change allows to easily configure the liveliness and readiness probe of the pods of all hono services.

feat: make hono probes configurable

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/infra/azure/arm/honoInfrastructureDeployment.json
charts/hono/infra/azure/arm/templates/kubernetesDeploy.json
charts/hono/infra/azure/arm/templates/serviceBusDeploy.json
charts/hono/infra/azure/arm/templates/vnetDeploy.json
charts/hono/infra/azure/managed-premium-retain.yaml

The instructions for setting up an AKS instance and installing Hono to
it have been cpoied from the Hono code base to the chart as proposed in
https://github.com/eclipse/hono/issues/2815

Add AKS instructions from Hono code base

---

charts/ditto/Chart.yaml
charts/ditto/templates/nginx-auth.yaml
charts/ditto/templates/nginx-deployment.yaml

switched from kind ConfigMap to Secret for nginx-auth;
adapted nginx-deployment.yaml to use the secret instead of the configmap;

Use Secret for nginx authentication

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/hono-service-auth/hono-service-auth-svc.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml

Changed configuration so that components now dynamically retrieve
validation key(s) from Auth server instead of requiring static
configuration of Auth server's public key.
Fixes #396

[#396] Use Hono 2.1.0 in Hono chart

---

NOTICE.md

Listing all copyright holders in the NOTICE file is not necessary and entries there were incomplete and not up-to-date.
See https://gitlab.eclipse.org/eclipse/technology/dash/org.eclipse.dash.handbook/-/issues/96
and the example NOTICE file [here](https://www.eclipse.org/projects/handbook/#legaldoc-notice).

Remove "Copyright holders" section from NOTICE file

---

charts/ditto/Chart.yaml
charts/ditto/requirements.yaml
charts/ditto/values.yaml

When testing the cloud2edge Helm chart version with the latest Ditto chart version (using the changes from #395), I noticed that the `ditto-mongodb` pod never got ready. There were always liveness/readiness check timeouts.
The issue here seems to be, that with the MongoDB chart version 11.2.0 (see #374), there is a considerably higher consumption of CPU and also memory resources due to the usage of the MongoDB `mongosh` tool instead of `mongo` for the health probes.
This is described and tracked in https://github.com/bitnami/charts/issues/10316, https://github.com/bitnami/charts/issues/10264 and [MONGOSH-1240](https://jira.mongodb.org/browse/MONGOSH-1240).
The last chart version that doesn't show this issue is 11.1.10. It uses the same MongoDB version as the 11.2.0 chart (MongoDB 4.4.13). …

Fix high CPU usage of Ditto mongodb container

---

charts/ditto/Chart.yaml
charts/ditto/templates/concierge-deployment.yaml
charts/ditto/templates/connectivity-deployment.yaml
charts/ditto/templates/gateway-deployment.yaml
charts/ditto/templates/policies-deployment.yaml
charts/ditto/templates/things-deployment.yaml
charts/ditto/templates/thingssearch-deployment.yaml

moved securityContext to container level in order to avoid breaking the container's non-root policy;
bump Chart version;
Fixes #402

Fix permissions issue when log files are enabled

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
charts/hono/templates/jaeger/jaeger-deployment.yaml
charts/hono/values.yaml

This PR adds the ability to add additional labels and annotations to PodSpecs in the hono chart on a per component basis.
Low level reasoning: I needed to inject connection secrets from HashiCorp Vault and the mutating webhook is triggered by adding the correct annotations.
I took the liberty to bump the chart version as well 😄

Hono: Allow adding additional labels and annotations to PodSpecs

---

.jenkins/Jenkinsfile
charts/hawkbit/Chart.yaml
charts/hawkbit/requirements.yaml

Use recommended URL for full bitnami index in hawkbit chart.
Add workaround for errors when packaging the hawkbit chart in the Jenkins pipeline.
Errors looked like this:
```
Building charts/hawkbit ...
+ dirname charts/hawkbit/Chart.yaml
+ /home/jenkins/agent/workspace/Website_master/helm package -u charts/hawkbit -d helm-repository
Error: no cached repository for helm-manager-91b1e65e9b2f631e58d61eb3d53eb80c2121816ad48f02d75a9bdb09bf9356b2 found. (try 'helm repo update'): open /home/jenkins/agent/workspace/Website_master/helm-cache/helm/repository/helm-manager-91b1e65e9b2f631e58d61eb3d53eb80c2121816ad48f02d75a9bdb09bf9356b2-index.yaml: no such file or directory
```
(see also https://github.com/eclipse/packages/issues/372#issuecomment-1149568041)

Update bitnami full index URL, fix Jenkins pipeline error

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/config/grafana/dashboard-definitions/message-details.json
charts/hono/config/grafana/dashboard-definitions/overview.json

Dashboards on grafana are not working because old metrics are used. This PR will fix it.
Mostly it was replacement of
_hono_messages_received_seconds_count_ =>
_hono_telemetry_processing_duration_seconds_count_
_hono_messages_payload_bytes_sum_ =>
_hono_telemetry_payload_bytes_sum_
_hono_commands_received_seconds_count_ =>
_hono_command_processing_duration_seconds_count_
_hono_commands_payload_bytes_sum_ =>
_hono_command_payload_bytes_sum_

Fixed Grafana dashboards to work with new metrics

---

charts/ditto/Chart.yaml
charts/ditto/templates/connectivity-deployment.yaml
charts/ditto/templates/policies-deployment.yaml
charts/ditto/templates/things-deployment.yaml
charts/ditto/templates/thingssearch-deployment.yaml

The secretKeyRef.name entry was composed differently in various deployments. It has been aligned for greater readability.

Align secretKeyRef.name with gateway-deployment

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/config/router/qdrouterd.json

This bug will cause that Hono chart will not start for this type of configuration of amqpMessagingNetworkExample

Wrong (misspelled) variable used for a host

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/config/router/qdrouterd.json
charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
charts/hono/templates/dispatch-router/dispatch-router-ext-svc.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-secret.yaml
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-svc.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-secret.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-svc.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-secret.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-svc.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-secret.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-svc.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-secret.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-svc.yaml
charts/hono/templates/hono-service-auth/hono-service-auth-secret.yaml
charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-ext-svc.yaml
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-secret.yaml
charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
charts/hono/values.yaml

This addresses #457
Do not expose insecure service port if insecure port is disabled for a component. Support disabling the insecure port of the Dispatch Router of the AMQP 1.0 based example messaging infrastructure.

Support disabling insecure ports

---

.github/CODEOWNERS

As I am currenlty not really involve in the project I think it makes sense to remove me as one of the code owners, in order to set the right expectations.
Being listed a code owner automatically assigns me as a reviewer to new PRs, however, I can't really review much and so people might wonder why I don't react.
So, removing me from the code owners file seems to be right way forward.

remove @ctron as code owner

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/requirements.yaml
packages/cloud2edge/values.yaml

Fix for #482 .
Fixes Hono devices registry not being able to connect to the MongoDB instance because it used the wrong hostname. Also fixes MongoDB not getting ready because the health checks took too long and caused OOM errors.
Also restrict Hono chart dependency version range (needed for upcoming changes addressing #430).

[#482] Fix wrong MongoDB hostname; fix MongoDB health checks.

---

homepage/_packages/cloud2edge/scripts/setCloud2EdgeEnv.sh
homepage/_packages/cloud2edge/tour.md
homepage/prereqs.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/post-install/demo-device-thing.json
packages/cloud2edge/post-install/hono-amqp-connection.json
packages/cloud2edge/post-install/hono-kafka-connection.json
packages/cloud2edge/requirements.yaml
packages/cloud2edge/templates/post-install-secret.yaml
packages/cloud2edge/values.yaml

Includes these commits:
- [#432]
Update ditto connection chapter in cloud2Edge tour.
Adding the request for creating a Kafka connection.
- [#486]
Update Ditto chart version in cloud2edge chart.
Using the Ditto chart from the Ditto repository now.
Also updated the tour to add instructions on using
the Ditto UI.
- Update cloud2Edge chart version to 0.5.0.

[#486] [#432] Update Ditto in cloud2edge chart, document creating Kafka connection in c2e tour

---

.jenkins/Jenkinsfile

Helm >= 3.8 needed to install cloud2edge chart now.

[#486] Use newer Helm version in Jenkinsfile.

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-pvc.yaml
charts/hono/values.yaml

Related to https://github.com/eclipse/packages/issues/478. 
Created a new parameter - storageSize - that allows any user to define the size of the storage created by the Service Device Registry pod. This allows the installation of the Hono in a Cloud Provider that have policies who restrict the size of the storage.

[#478] Invalid PVC Size

---

homepage/_packages/cloud2edge/tour.md

The curl command in the [Receiving a command at the device](https://www.eclipse.org/packages/packages/cloud2edge/tour/#receiving-a-command-at-the-device) chapter was not returning the command that was sent to Ditto via
```
curl -i -X POST -u ditto:ditto -H 'Content-Type: application/json' -w '\n' --data '{
"water-amount": "3liters"
}' ${DITTO_API_BASE_URL:?}/api/2/things/org.eclipse.packages.c2e:demo-device/inbox/messages/start-watering?timeout=0
```
as written in the "Sending a command to the device via its digital twin" chapter.

Fix curl command in 'Receiving command at device' c2e tour section.

---

homepage/_packages/cloud2edge/installation.md
homepage/prereqs.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/values.yaml

This fixes #433.
I've restored the original service-type NodePort as default for the cloud2edge chart and adapted the "helm install" command for using service-type LoadBalancer.
I've also revised the "Prerequisites" page, replacing outdated links there and changing the MicroK8s chapter. The general "Loadbalancing and Ingress" in that chapter seemed out-of-place there to me. It also contained specific cloud2edge package information, which should rather go in the cloud2edge package installation instructions. The "Ingress LoadBalancing" section contained outdated information regarding the Ambassador component. I've therefore removed the "Loadbalancing and Ingress" chapter there.

[#433] Use consistent LB/NodePort setting in c2e chart, fix c2e docs.

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
charts/hono/templates/hono-adapter-base/hono-adapter-role.yaml
charts/hono/templates/hono-adapter-base/hono-adapter-rolebinding.yaml
charts/hono/templates/hono-adapter-base/hono-adapter-sa.yaml
charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
charts/hono/values.yaml

This fixes #512.
Apply changes needed for https://github.com/eclipse-hono/hono/pull/3546, adding corresponding service accounts.
Also update jaegertracing/all-in-one and opentelemetry-collector image versions and fix Hono chart icon URL.

[#512] Add service account for Hono adapter pods; update tracing image versions.

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/example/add_example_data_device_registry.sh

Updated to bitnami/kafka chart version 21.x which uses Kafka 3.4.
This aligns better with the Kafka version being used for testing in Hono
2.4.

Update to kafka 3.4

---

CONTRIBUTING.md
homepage/contribute.md

Removing the 'Signed-off-by' requirement as it isn't listed in the [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#resources-commit) anymore.
See the corresponding change in the `org.eclipse.dash.handbook` repo [here](https://gitlab.eclipse.org/eclipse/technology/dash/org.eclipse.dash.handbook/-/commit/ba80975702f666de587e9cd0003d821cb8f95d9a#13e7b2e3a22176dcc2d2d157775b7732dff45899_91_88).

Update commit requirements in Contributing page.

---

charts/hawkbit/Chart.yaml
charts/hawkbit/templates/deployment.yaml
charts/hawkbit/values.yaml

This allow to specify a full springDatasourceUrl instead of create url from springDatasourceHost and springDatasourceDb.

Allow other database than mysql

---

charts/hono/README.md
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/values.yaml

This is for #522, to be included in PR #523:
Adds support for the `useLegacyTraceContextFormat` property introduced in Hono 2.5.0 (https://github.com/eclipse-hono/hono/issues/3597).

[#522] Hono 2.5.0: Add useLegacyTraceContextFormat property in values.yaml.

---

charts/hono/Chart.yaml
charts/hono/README.md
charts/hono/ci/datagrid-values.yaml
charts/hono/ci/mongodb-based-device-registry-values.yaml
charts/hono/ci/quarkus-native-images-values.yaml
charts/hono/templates/NOTES.txt
charts/hono/templates/_helpers.tpl
charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
charts/hono/values.yaml

Changed configuration to run Apache Kafka in KRaft mode.
Fixes #522

[#522] Update to Hono 2.5.0

---

homepage/_packages/cloud2edge/installation.md
homepage/_packages/cloud2edge/tour.md
packages/cloud2edge/Chart.yaml
packages/cloud2edge/README.md
packages/cloud2edge/profileAmqpMessaging-values.yaml
packages/cloud2edge/values.yaml

[#533] Update c2e chart to use Hono 2.6.1, Ditto 3.5.6.

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/README.md
packages/cloud2edge/templates/NOTES.txt

Updates the cloud2edge chart with the new Hono chart, including the updated example certificates (#543). Ditto version is updated as well.

[#543] Update Hono/Ditto versions in c2e chart.

---

charts/hawkbit/Chart.yaml
charts/hawkbit/templates/_helpers.tpl
charts/hawkbit/templates/ingress.yaml
charts/hawkbit/values.yaml

Cherrypicked the commit from #314 and added a commit to update the chart version.

Hawkbit: Use networking.k8s.io/v1 for Ingress if available (2)

---

charts/hawkbit/Chart.yaml
charts/hawkbit/templates/deployment.yaml
charts/hawkbit/templates/tests/test-connection.yaml
charts/hawkbit/values.yaml

In the current version, the helm chart does not support the latest version of hawkBit that is [0.5.0].
Because of the removal of the vaadin UI, the readyness and liveness probes are broken.
Additionally, by default, the version [0.5.0] uses the [MariaDB Connector][MariaDB-j] instead of the [MySQL Connector][mysql-j].
Thus, I updated the readiness and liveness probes to use the Swagger-UI and the MariaDB connection string by default.
[0.5.0]: https://github.com/eclipse/hawkbit/releases/tag/0.5.0 
[MariaDB-j]: https://mariadb.com/kb/en/about-mariadb-connector-j/
[mysql-j]: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j

Update hawkBit to Application Version 0.5.0

---

packages/cloud2edge/Chart.yaml
packages/cloud2edge/README.md

[#557] Update c2e chart to use Hono 2.6.4.

---

.github/ct.yaml
.github/kubeval.sh
.jenkins/Jenkinsfile
NOTICE.md
README.md
homepage/_config_staging.yml
homepage/contribute.md
homepage/prereqs.md
homepage/repository.md

This is for #560.
I've also removed usage of `https://staging.eclipse.org/packages/charts` in the `Jenkinsfile`. I guess this doesn't work anymore since the website moved from Gerrit to GitHub (as stated [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2689)).

[#560] Update links to point to eclipse.dev/packages.
