- charts/ditto/Chart.yaml
- charts/ditto/values.yaml
Changes for Ditto 1.0.0 release.
Please do not merge until docker images become available.
> Bump Ditto version

- charts/ditto/Chart.yaml
- charts/ditto/README.md
- charts/ditto/requirements.yaml
Signed-off-by: Axel Köhler <axel.koehler@kiwigrid.com>
This PR contains only minor changes, but will create the 1.0.0 chart.
> Ditto Helm chart 1.0.0 version with minor changes

- .github/check-for-chart-changes.sh
- homepage/repository.md
Signed-off-by: Axel Köhler <axel.koehler@kiwigrid.com>
> Add info about chart publishing

- charts/ditto/Chart.yaml
- charts/ditto/README.md
Fixed typo in README.md
relm -> helm
Signed-off-by: Patrick Sernetz <patrick@sernetz.com>
> Fixed typo in README.md

- charts/hawkbit/.helmignore
- charts/hawkbit/Chart.yaml
- charts/hawkbit/README.md
- charts/hawkbit/requirements.lock
- charts/hawkbit/requirements.yaml
- charts/hawkbit/templates/NOTES.txt
- charts/hawkbit/templates/_helpers.tpl
- charts/hawkbit/templates/configmap.yaml
- charts/hawkbit/templates/deployment.yaml
- charts/hawkbit/templates/ingress.yaml
- charts/hawkbit/templates/poddisruptionbudget.yaml
- charts/hawkbit/templates/secrets.yaml
- charts/hawkbit/templates/service.yaml
- charts/hawkbit/templates/tests/test-connection.yaml
- charts/hawkbit/values.yaml
Signed-off-by: Axel Köhler <axel.koehler@kiwigrid.com>
This PR will add the Hawkbit update server chart to the packages project.
Feedback is highly appreciated.
> Add chart for HawkBit

- charts/hono/Chart.yaml
- charts/hono/README.md
The instructions are mostly copied from the Hono project.
> Add detailed installation instructions

- .github/workflows/ci.yaml
This should set up the CI pipeline to also test packages
> Enable CI pipeline for packages

- charts/ditto/Chart.yaml
- charts/ditto/templates/nginx-configmap.yaml
- charts/ditto/values.yaml
+ fixed nginx conf for correctly displaying icons
> Ditto chart: added defaults for resources.requests cpu and memory config

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/templates/NOTES.txt
Also added iot-package key word to Chart.yaml to support filtering for
packages when searching repository.
> Add NOTES.txt referring to Cloud2Edge home page

- charts/ditto/Chart.yaml
The key word can be used to filter for project charts when searching the
repository.
> Add iot-chart key word to Ditto Chart.yaml

- charts/ditto/Chart.yaml
- charts/ditto/templates/swaggerui-deployment.yaml
The values.yaml file provides a property for setting resource
requests/limits for the Swagger UI. However, the corresponding
deployment did not use this property yet.
> Use resource definitions from values.yaml

- homepage/_packages/cloud2edge/installation.md
- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/example-credentials.json
- packages/cloud2edge/example-device-identities.json
- packages/cloud2edge/example-permissions.json
- packages/cloud2edge/example-tenants.json
- packages/cloud2edge/values.yaml
Use NodePort for Ditto's nginx service.
> Use NodePort or Ditto's nginx service

- charts/ditto/Chart.yaml
- charts/ditto/templates/nginx-service.yaml
- charts/ditto/values.yaml
when nginx was configured with "type: NodePort"
> Ditto chart: added possibility to define nodePort 

- homepage/_packages/cloud2edge/tour.md
Enhanced 2 things:
* using Ditto messages to the twin in order to send downstream commands to the Hono device and optionally answer to those (encountered a bug in the created connection in the package fixed by #55)
* creating additional digital twins
> Enhanced "tour" documentation of c2e package by creating twins and sending commands

- homepage/contribute.md
- homepage/repository.md
- added hint for updating newly added repository
- documented requirement regarding key words in Chart.yaml
> Improve documentation

- charts/hono/Chart.yaml
- charts/hono/README.md
Signed-off-by: Soheila Dehghanzadeh <s.dehghanzadeh@denso-auto.de>
> Added ecplise- prefix to service names in the readme of hono chart

- charts/ditto/Chart.yaml
- charts/ditto/templates/nginx-configmap.yaml
> Configmap for Nginx should not be deploy when nginx is disabled

- homepage/contribute.md
Based on the discussion on Gitter I think that it seems reasonable to explicitly describe some circumstances that would/should require a change of a chart's version. Some of the more obvious
cases are documented in the contribution guide. These can serve as a basis for further additions and or changes.
This PR is supposed to serve as a straw man for discussing the subject and coming to an agreement on at least a few basic rules.
> Add chart version change hints

- charts/hono/Chart.yaml
- charts/hono/config/router/qdrouterd.json
- charts/hono/example/example-credentials.json
- charts/hono/values.yaml
Also aligned the PSK credentials of the demo device with the ones used
for the Hono sandbox.
> Upgrade to Hono 1.2.0

- homepage/Gemfile.lock
- homepage/_packages/cloud2edge/tour.md
- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/templates/post-install-job.yaml
Connecting to a newly created Hono tenant.
Also removed "timeout" from c2e chart template as this parameter is no longer required.
Fixes #97
> Enhanced cloud2edge "tour" by adding a new Ditto connection

- charts/hono/Chart.yaml
- charts/hono/README.md
Signed-off-by: Kai Hudalla <kai.hudalla@bosch.io>
> Document how to use specific, non-standard images

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/requirements.yaml
> configured c2e package to use Ditto 1.1.0

- charts/hono/Chart.yaml
- charts/hono/values.yaml
Upgraded to version used for running Hono integration tests.
Also upgraded to Artemis service release 2.10.1-1.
> Use Qpid Dispatch Router 1.12.0

- charts/ditto/Chart.yaml
- charts/ditto/templates/concierge-deployment.yaml
- charts/ditto/templates/connectivity-deployment.yaml
- charts/ditto/templates/gateway-deployment.yaml
- charts/ditto/templates/nginx-deployment.yaml
- charts/ditto/templates/policies-deployment.yaml
- charts/ditto/templates/swaggerui-deployment.yaml
- charts/ditto/templates/things-deployment.yaml
- charts/ditto/templates/thingssearch-deployment.yaml
- charts/ditto/values.yaml
Adjustments to c2e package will follow in a separate PR
> update Eclipse Ditto chart to Ditto 1.2.0

- homepage/_packages/cloud2edge/tour.md
added to Ditto 1.2.0 (e.g. at least once delivery based on Hono "qos" header)
> updated cloud2edge package "tour" with the new connection options

- charts/hono/Chart.yaml
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
> mongoDb secret is faulty when overriding the mongodb settings for mongoDBBasedDeviceRegistry

- charts/hono/Chart.yaml
- charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-post-install-job.yaml
- charts/hono/values.yaml
> allow users to turn off example data in the device registry

- charts/hono/Chart.yaml
- charts/hono/values.yaml
> Update documentation on device connection service

- charts/hono/Chart.yaml
- charts/hono/config/artemis/broker.xml
This fixes #168:
This fixes the issue of queues not getting created when event messages are sent and of event messages getting forwarded to multiple consumers.
> [#168] Use ANYCAST routing type in broker config

- charts/hono/Chart.yaml
- charts/hono/values.yaml
Upgraded
* Infinispan Server to 11.0.7.
* Qpid Dispatch Router to 1.14.0
* Artemis to 2.13.0
* Jaeger Agent and Collector to 1.21
> Upgrade several components to latest versions

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/ci/ci-values.yaml
- charts/hono/ci/datagrid-values.yaml
- charts/hono/ci/device-connection-service-values.yaml
- charts/hono/values.yaml
Also remove the "experimental" status for the CoAP adapter (fully supported since Hono 1.5).
> Add Jaeger Tracing chapter, minor fixes

- charts/ditto/Chart.yaml
> update ditto appVersion to 1.5.1

- homepage/prereqs.md
With this PR we propose to extend the documentation of the prerequisites to the case were one wants to run Kubernetes locally. In the described approach we use MicroK8s. Please note that @LuLeRoemer joined the efforts for this PR.
> adds documentation for local Kubernetes deployment based on MicroK8s

- charts/hono/Chart.yaml
- charts/hono/templates/_helpers.tpl
> allow specifying custom certificates for adapters

- charts/hono/Chart.yaml
- charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
- charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
- charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
Added support for deploying Quarkus based variants of AMQP and CoAP
adapters and Auth service.
> Support deployment of additional Quarkus based components

- charts/hono/Chart.yaml
- charts/hono/values.yaml
> raise commandRouter memory limit to 512Mi

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/config/command-router/embedded-cache-config.xml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-pvc.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
- charts/hono/values.yaml
Also update to Hono 1.6.1.
This fixes #213 and applies the fix for https://github.com/eclipse/hono/issues/2576.
> [#213] Use file cache store for embedded cache

- charts/hono/Chart.yaml
- charts/hono/config/infinispan/hono-data-grid.xml
> Add BULK_READ permission to adapter role in datagrid

- charts/hawkbit/Chart.yaml
- charts/hawkbit/requirements.yaml
- charts/hawkbit/values.yaml
This fixes #211 by updating the rabbitmq chart to ~~the latest~~ a later version.
Also fixes wrong indentation of the `metrics` config element.
> [#211] Hawkbit: Update rabbitmq chart version

- charts/hono/Chart.yaml
- charts/hono/templates/_helpers.tpl
The Quarkus based native adapter images require the configuration
properties in application.yml to be all camel case.
Fixes #230
> Use camel case for resource limit checks configuration

- charts/ditto/Chart.yaml
- charts/ditto/values.yaml
Latest bugfix was released today:
https://www.eclipse.org/ditto/release_notes_201.html
> updated the Ditto chart to the latest bugfix version 2.0.1

- charts/hono/Chart.yaml
- charts/hono/templates/hono-adapter-coap/hono-adapter-coap-vertx-secret.yaml
> [#223] Add CoAP X.509 support

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/requirements.yaml
Upgraded to
- Ditto 2.0.1
- Hono 1.8.0
> Upgrade dependencies

- charts/hono/Chart.yaml
> Upgrade to Hono 1.9.0

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/templates/_helpers.tpl
- charts/hono/values.yaml
> [#249] Hono: Make Device registry with "embedded" DB the default

- charts/ditto/Chart.yaml
- charts/ditto/templates/concierge-deployment.yaml
- charts/ditto/templates/connectivity-deployment.yaml
- charts/ditto/templates/mongodb-secret.yaml
- charts/ditto/templates/policies-deployment.yaml
- charts/ditto/templates/things-deployment.yaml
- charts/ditto/templates/thingssearch-deployment.yaml
- charts/ditto/values.yaml
> ditto: configure ditto mongodb connection via an external secret

- charts/hono/Chart.yaml
- charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-post-install-configmap.yaml
> [#276] Hono: Add CA configuration for DEFAULT_TENANT

- charts/ditto/Chart.yaml
- charts/ditto/ci/ingress-values.yaml
- charts/ditto/templates/nginx-ingress.yaml
+ added ci/ingress-values.yaml in order to lint the generated k8s templates with ingress enabled
> Fixed Ditto's nginx ingress template

- charts/ditto/Chart.yaml
- charts/ditto/templates/concierge-deployment.yaml
- charts/ditto/templates/connectivity-deployment.yaml
- charts/ditto/templates/gateway-deployment.yaml
- charts/ditto/templates/policies-deployment.yaml
- charts/ditto/templates/things-deployment.yaml
- charts/ditto/templates/thingssearch-deployment.yaml
- charts/ditto/values.yaml
This PR updates the Ditto Helm chart to use Ditto version 2.1.0
> Ditto 2.1.0 Helm chart

- charts/hono/Chart.yaml
- charts/hono/values.yaml
Also updated Jaeger Agent to 1.26
> Update to Hono 1.10.0

- charts/ditto/Chart.yaml
- charts/ditto/templates/nginx-deployment.yaml
- charts/ditto/values.yaml
> #295: make ditto-nginx init container image configurable

- charts/ditto/Chart.yaml
- charts/ditto/README.md
- charts/ditto/templates/concierge-deployment.yaml
- charts/ditto/templates/connectivity-deployment.yaml
- charts/ditto/templates/gateway-deployment.yaml
- charts/ditto/templates/policies-deployment.yaml
- charts/ditto/templates/things-deployment.yaml
- charts/ditto/templates/thingssearch-deployment.yaml
* switched from "toYaml" to "range"
Probably caused https://github.com/eclipse/ditto/issues/1201
> fixed Ditto systemProps was omitting double quotes

- homepage/prereqs.md
> Fix link to CNCF's kubernetes platform options page

- .github/workflows/ci.yaml
- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/ci/datagrid-values.yaml
- charts/hono/ci/device-connection-service-values.yaml
- charts/hono/ci/mongodb-based-device-registry-values.yaml
- charts/hono/ci/monitoring-values.yaml
- charts/hono/ci/quarkus-native-images-values.yaml
- charts/hono/values.yaml
The README has been updated accordingly.
Fixes #316
> Do not install Prometheus and Grafana by default.

- charts/hono/Chart.yaml
- charts/hono/README.md
Some improvements regarding wording and structuring
> Improve Hono chart README

- charts/ditto/Chart.yaml
- charts/ditto/README.md
- charts/ditto/values.yaml
* simplified README.md of the Ditto chart; added namespace, borrowed from Hono readme
> Update Ditto Helm chart to released Ditto 2.2.0

- charts/hono/Chart.yaml
- charts/hono/config/infinispan/hono-data-grid.xml
- charts/hono/templates/example-data-grid/statefulset.yaml
- charts/hono/values.yaml
Follow-up of #326:
Update Infinispan image to 13.0.5, using again the native image version.
> Update to infinispan/server-native:13.0.5

- charts/hono/Chart.yaml
- charts/hono/ci/mongodb-based-device-registry-values.yaml
- charts/hono/config/router/qdrouterd.json
- charts/hono/templates/NOTES.txt
- charts/hono/templates/_helpers.tpl
- charts/hono/templates/artemis/artemis-deployment.yaml
- charts/hono/templates/artemis/artemis-secret.yaml
- charts/hono/templates/artemis/artemis-svc.yaml
- charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
- charts/hono/templates/dispatch-router/dispatch-router-ext-svc.yaml
- charts/hono/templates/dispatch-router/dispatch-router-route.yaml
- charts/hono/templates/dispatch-router/dispatch-router-secret.yaml
- charts/hono/templates/dispatch-router/dispatch-router-svc.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
- charts/hono/templates/hono-service-device-connection/hono-service-device-connection-secret.yaml
- charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml
- charts/hono/templates/hono-service-device-registry-file/hono-service-device-registry-secret.yaml
- charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-secret.yaml
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-secret.yaml
- charts/hono/values.yaml
This addresses #324 and #325
Upgraded to Hono 1.11.1
> Upgrade to Hono 1.11

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/templates/NOTES.txt
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
- charts/hono/values.yaml
The chart now uses Hono 1.12.0 images by default.
Fixes #341
> [#341] Upgrade to Hono 1.12.0

- charts/ditto/Chart.yaml
- charts/ditto/templates/concierge-deployment.yaml
- charts/ditto/templates/connectivity-deployment.yaml
- charts/ditto/templates/gateway-deployment.yaml
- charts/ditto/templates/policies-deployment.yaml
- charts/ditto/templates/things-deployment.yaml
- charts/ditto/templates/thingssearch-deployment.yaml
- charts/ditto/values.yaml
* and adjusted from OpenJ9 JVM args to Hotspot args
* updated to new logging env variable options
Fixes: #352
> [#352] update Ditto chart to Ditto 2.4.0

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/requirements.yaml
- packages/cloud2edge/values.yaml
> Update c2e package to use Ditto 2.4.0

- charts/ditto/Chart.yaml
- charts/ditto/requirements.yaml
- charts/ditto/values.yaml
use mongodb version 4.4.13;
update mongodb config to disable authentication;
> Update mongodb chart version to 11.2.0

- charts/hono/Chart.yaml
- charts/hono/templates/_helpers.tpl
- charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
- charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
- charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
- charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
- charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
- charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
- charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
- charts/hono/values.yaml
Signed-off-by: Bob Claerhout <bob.claerhout@aloxy.io>
> allow setting annotations on hono deploys

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/post-install/hono-kafka-connection.json
The credentials were always assumed to be those for the example one.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> Fix c2e's Kafka setup when using an external cluster

- .github/workflows/ci.yaml
BEFORE MERGING the Chart version needs to be reset to its original value ...
> Update k8s versions being used for deployment tests

- charts/hono/Chart.yaml
- charts/hono/README.md
Use latest Hono service release
> Use Hono 2.1.1 container images

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/templates/hono-service-command-router/hono-service-command-router-secret.yaml
> [#434] Update to Hono 2.2.0

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/values.yaml
Updated Bitnami Kafka chart to version 20.x.
Updated Bitnami MongoDB chart to version 13.x.
Also configured upper limit for Kafka and Zookeeper JVMs memory consumption.
> [Hono] Update to latest Bitnami chart versions

- charts/hono/Chart.yaml
- charts/hono/README.md
> [#447] Update to Hono 2.3.0

- charts/ditto/Chart.yaml
- charts/ditto/templates/nginx-configmap.yaml
> #466 add connections API endpoint into nginx-configmap.yaml

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/templates/_helpers.tpl
- charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
- charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
- charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
- charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
- charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
- charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
- charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
- charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
- charts/hono/templates/jaeger/jaeger-deployment.yaml
- charts/hono/values.yaml
This is an extension on #279 to also allow secrets to be used as environment variables.
Signed-off-by: Mathias Maes mathias@maes.family
> Allow secretRef's in envFrom fields

- charts/hono/Chart.yaml
- charts/hono/README.md
> Use Hono 2.4.0 container images

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/example/add_example_data_device_registry.sh
- charts/hono/infra/azure/arm/honoInfrastructureDeployment.json
- charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-post-install-job.yaml
> [#490] Pin MongoDB chart version, apply minor fixes.

- homepage/_packages/cloud2edge/tour.md
- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/post-install/hono-amqp-connection.json
- packages/cloud2edge/post-install/hono-kafka-connection.json
- packages/cloud2edge/post-install/post-install.sh
- packages/cloud2edge/values.yaml
> [#499] [#501] Cloud2edge: Fix ditto resource config, use Connections API.

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/templates/_helpers.tpl
- charts/hono/templates/artemis/artemis-deployment.yaml
- charts/hono/templates/dispatch-router/dispatch-router-deployment.yaml
- charts/hono/templates/example-data-grid/statefulset.yaml
- charts/hono/templates/hono-adapter-amqp/hono-adapter-amqp-deployment.yaml
- charts/hono/templates/hono-adapter-coap/hono-adapter-coap-deployment.yaml
- charts/hono/templates/hono-adapter-http/hono-adapter-http-deployment.yaml
- charts/hono/templates/hono-adapter-lora/hono-adapter-lora-deployment.yaml
- charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-deployment.yaml
- charts/hono/templates/hono-service-auth/hono-service-auth-deployment.yaml
- charts/hono/templates/hono-service-command-router/hono-service-command-router-deployment.yaml
- charts/hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-statefulset.yaml
- charts/hono/templates/hono-service-device-registry-jdbc/hono-service-device-registry-deployment.yaml
- charts/hono/templates/hono-service-device-registry-mongodb/hono-service-device-registry-deployment.yaml
- charts/hono/templates/jaeger/jaeger-deployment.yaml
- charts/hono/values.yaml
> [#494] add priorityClass support

- packages/cloud2edge/Chart.yaml
- packages/cloud2edge/README.md
- packages/cloud2edge/post-install/post-install.sh
- packages/cloud2edge/profileTracing-values.yaml
Also apply minor fix in post-install.sh, using the appropriate protocol for registering the default
tenant and device (adopted from 6cf96a989a083ab94461ffe6171be4e5cffd1bf2).
> Use Ditto 3.4.0, Hono 2.5.6 in c2e chart.

- charts/hono/Chart.yaml
- charts/hono/README.md
- charts/hono/values.yaml
> [#531] Update to Hono 2.5.1.
